apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: mkislam2015/flask-api:1.0.0
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: weather-api-secret
        

